config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  root to: "tasks#index"
  post '/tasks/:id/done' => 'tasks#done',   as: 'done'
  post '/tasks/:id/wip' => 'tasks#wip',   as: 'wip'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  include ActiveHash::Associations
  has_many :tasks

  field :name 
  self.data = [
    {id: 0, name: 'none'}, 
    {id: 1, name: 'work'}, 
    {id: 2, name: 'life'},
    {id: 3, name: 'hobby'}, 
    {id: 4, name: 'other'}
  ]
end

app/models/task.rb
class Task < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category
  belongs_to :user

  validates :title, :start_date, :end_date, :category_id, :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks

  validates :name, :email, :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth, if: :production?
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = [:name]
    devise_parameter_sanitizer.permit(:sign_up, keys: added_attrs)
    devise_parameter_sanitizer.permit(:account_update, keys: added_attrs)
  end

  private

  def production?
    Rails.env.production?
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == Rails.application.credentials.basic_auth[:basic_auth_user] && password == Rails.application.credentials.basic_auth[:basic_auth_password]
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :done, :wip]

  def index
    @tasks = Task.where(user_id: current_user.id).includes(:user) if user_signed_in?
  end

  def show
  end

  def new
    if user_signed_in?
      @task = Task.new
    else
      redirect_to tasks_path
    end
  end

  def edit
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def done
    @task.update(status: "Done")
    @tasks = Task.all.includes(:user)
  end

  def wip
    @task.update(status: "WIP")
    @tasks = Task.all.includes(:user)
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :start_date, :end_date, :category_id, :status).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/done_wip/_done_wip.html.erb
<% if task.status == "Done" %>
  <%= link_to 'WIP', wip_path(task), method: :post, remote: true, class: "btn btn-warning" %>
<% else %>
  <%= link_to 'Done', done_path(task), method: :post, remote: true, class: "btn btn-info" %>
<% end %>

app/views/layouts/_header.html.erb
<div id="contents_header">
  <nav class="globalnav">
    <div class="globalnav__menu">
      <ul class="gmenu">
        <li class="logo" style="float: left">
          <a href="/">Calendar Task</a>
        </li>
        <% if user_signed_in? %>
        <li class="entry_button" style="float: right">
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
        </li>
        <li class="entry_button" style="float: right">
          <%= link_to "Sign In User Name : #{current_user.name}", edit_user_registration_path %>
        </li>
        <% else %>
        <li class="entry_button" style="float: right">
          <%= link_to 'Log in', new_user_session_path %>
        </li>
        <li class="entry_button" style="float: right">
          <%= link_to 'Sign up', new_user_registration_path %>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CalendarTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="form-content">
  <%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>
    <ul>
      <% task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="form-group">
    <%= form.label "Title" %>
    <%= form.text_field :title, class:"form-control", id:"exampleInputEmail1", placeholder:"title"%>
  </div>
  <div class="form-group">
    <%= form.label "Content" %>
    <%= form.text_area :content, class:"form-control", id:"exampleFormControlTextarea1", placeholder:"content" %>
  </div>
  <div class="form-group">
    <%= form.label "Start_Date" %>
    <%= form.datetime_select :start_date, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label "End_Date" %>
    <%= form.datetime_select :end_date, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= form.label "Category" %>
    <%= form.collection_select :category_id, Category.all, :id, :name %>
  </div>

  <div class="form-group">
    <%= form.label "Status" %>
    <%= form.select :status, ["New","WIP","Done","Pending"] %>
  </div>

  <div class="actions">
    <% if controller.controller_name == 'tasks' && controller.action_name == 'edit' %>
    <button class="btn btn-outline-primary" type="submit">Update Task</button>
    <%= link_to 'Back', @task,  class:"btn btn-outline-secondary" %>
    <%else%>
    <button class="btn btn-outline-primary" type="submit">Create Task</button>
    <%= link_to 'Back', tasks_path,  class:"btn btn-outline-secondary" %>
    <%end%>
  </div>
  <% end %>
</div>

app/views/tasks/_task.html.erb
<tr>
  <div class="card" id="task-info">
    <div class="card-header">
      <%= link_to task.title, task ,class: 'fc-event'%>
      <div id="task<%= task.id %>">
        <h4>Status:<%= task.status %></h4>
      </div>
      <% if user_signed_in? && task.user.id == current_user.id %>
      <div class="button-right" id="button<%= task.id %>"><%= render 'done_wip/done_wip', task: task %></div>
      <% end %>
    </div>
    <div class="card-body">
      <div class="float-left">
        <h4>【<%= task.category.name %>】</h4>
      </div>
      <div class="float-right">
        <% if user_signed_in? && task.user.id == current_user.id %>
        <%= link_to 'Edit', edit_task_path(task), class: "btn btn-outline-primary"%>
        <%= link_to 'Destroy', task, method: :delete, class: "btn btn-outline-danger", data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  </div>
</tr>

app/views/tasks/done.js.erb
$('#task<%= @task.id %>').html('<h4>Status:Done</h4>');
$('#button<%= @task.id %>').html('<%= escape_javascript(render("done_wip/done_wip", task: @task )) %>')

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div id='wrap'>
  <div id='external-events'>
    <div class="card">
      <div class="card-header">
        <h4 class="task-head">My Tasks</h4>
        <% if user_signed_in? %><%= link_to 'New Tasks', new_task_path, class: "btn btn-outline-success", id: "new-task"%><%end%>
      </div>
      <div class="card-body" id="task-box">
        <div id="scroll-bar">
          <blockquote class="blockquote mb-0">
            <%= render :partial => 'task', :collection => @tasks %>
          </blockquote>
        </div>
      </div>
    </div>
  </div>

  <div id='calendar'></div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="form-content">
  <div class="card">
    <div class="card-header">
      <h4>
        <strong>Title:</strong>
        <%= @task.title %>
      </h4>
      <h5>
        <strong>Content:</strong>
        <%= @task.content %>
      </h5>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <h5>
          <strong>Start_date:</strong>
          <%= @task.start_date %>
        </h5>
        <h5>
          <strong>End_date:</strong>
          <%= @task.end_date %>
        </h5>
        <h5>
          <strong>Category:</strong>
          <%= @task.category.name %>
        </h5>
        <h5>
          <strong>Status:</strong>
          <%= @task.status %>
        </h5>
        <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-outline-primary" %> 
        <%= link_to 'Back', tasks_path, class: "btn btn-outline-secondary" %>
      </blockquote>
    </div>
  </div>
</div>

app/views/tasks/wip.js.erb
$('#task<%= @task.id %>').html('<h4>Status:WIP</h4>');
$('#button<%= @task.id %>').html('<%= escape_javascript(render("done_wip/done_wip", task: @task )) %>')